apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app.fullname" . }}
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: {{ include "app.name" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: web
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: db